# Integer AppMessage values used by `send_emulator_configuration`.
# Key IDs follow package.json messageKeys numbering (10000 + index).

# SortOrder (0=MRU, 1=Shortest first, 2=Longest first)
EMULATOR_CFG_SORT_ORDER_KEY := 10001
EMULATOR_CFG_SORT_ORDER_VAL := 1

# AutoReturnStart (0=off, 1=on)
EMULATOR_CFG_AUTORETURN_START_KEY := 10003
EMULATOR_CFG_AUTORETURN_START_VAL := 0

# AutoReturnStop (0=off, 1=on)
EMULATOR_CFG_AUTORETURN_STOP_KEY := 10018
EMULATOR_CFG_AUTORETURN_STOP_VAL := 0

# RunningFirst (0=off, 1=on)
EMULATOR_CFG_RUNNINGFIRST_KEY := 10004
EMULATOR_CFG_RUNNINGFIRST_VAL := 1

# IdleExitSec (0=off, else timeout in seconds)
EMULATOR_CFG_IDLEEXIT_KEY := 10011
EMULATOR_CFG_IDLEEXIT_VAL := 0

# CfgOpen (0=phone config closed, 1=open; use 0 for emulator config push)
EMULATOR_CFG_CFGOPEN_KEY := 10012
EMULATOR_CFG_CFGOPEN_VAL := 0

# LaunchSync (0=off, 1=on)
EMULATOR_CFG_LAUNCHSYNC_KEY := 10013
EMULATOR_CFG_LAUNCHSYNC_VAL := 1

# DefaultFinishAction (0=Save, 1=Delete) - default "After finished" for new timers
EMULATOR_CFG_DEFAULTFINISHACTION_KEY := 10014
EMULATOR_CFG_DEFAULTFINISHACTION_VAL := 1

# RunOnCreate (0=off, 1=on) - run a newly created timer immediately
EMULATOR_CFG_RUNONCREATE_KEY := 10015
EMULATOR_CFG_RUNONCREATE_VAL := 1

# Final `--int` argument list passed to pebble send-app-message.
EMULATOR_CFG_INT_ARGS := \
	$(EMULATOR_CFG_SORT_ORDER_KEY)=$(EMULATOR_CFG_SORT_ORDER_VAL) \
	$(EMULATOR_CFG_AUTORETURN_START_KEY)=$(EMULATOR_CFG_AUTORETURN_START_VAL) \
	$(EMULATOR_CFG_AUTORETURN_STOP_KEY)=$(EMULATOR_CFG_AUTORETURN_STOP_VAL) \
	$(EMULATOR_CFG_RUNNINGFIRST_KEY)=$(EMULATOR_CFG_RUNNINGFIRST_VAL) \
	$(EMULATOR_CFG_IDLEEXIT_KEY)=$(EMULATOR_CFG_IDLEEXIT_VAL) \
	$(EMULATOR_CFG_CFGOPEN_KEY)=$(EMULATOR_CFG_CFGOPEN_VAL) \
	$(EMULATOR_CFG_LAUNCHSYNC_KEY)=$(EMULATOR_CFG_LAUNCHSYNC_VAL) \
	$(EMULATOR_CFG_DEFAULTFINISHACTION_KEY)=$(EMULATOR_CFG_DEFAULTFINISHACTION_VAL) \
	$(EMULATOR_CFG_RUNONCREATE_KEY)=$(EMULATOR_CFG_RUNONCREATE_VAL)
