#!/usr/bin/env bash
# Generic functional-test-sequence interpreter for Pebble apps.
#
# App-agnostic: everything app-specific (UUID, platform, whether to run
# --vnc by default) comes from a small `--conf` KEY=value file, not from
# anything hardcoded here. See README.md in this directory for the full
# instruction-set reference and an app.conf example.
#
# Usage:
#   run_sequence.sh --conf <app.conf> --seq <sequence_file> [options]
#
# Options:
#   --conf FILE            App config file (APP_UUID=, PLATFORM=, VNC=0|1).
#   --seq FILE              Top-level .seq file to run.
#   --platform NAME         Override PLATFORM from the conf file.
#   --vnc / --no-vnc         Override VNC from the conf file.
#   --out-dir DIR            Base output dir (default: <dir of conf>/out).
#   --run-id ID              Use this instead of generating a fresh
#                            timestamp for this run's output directory
#                            (<out-dir>/<ID>/<sequence-name>/) - lets a
#                            caller running several sequences as one batch
#                            (see tests/functional/run_all.sh) group them
#                            all under one shared timestamp instead of each
#                            sequence getting its own. Default: a fresh
#                            `date +%Y%m%d_%H%M%S` generated by this run.
#   --continue-on-error      Keep running after a failed step instead of
#                            stopping immediately; reports a summary at the
#                            end.
#   --golden-dir DIR         Base dir of approved (golden) baselines, one
#                            subdirectory per sequence (named after the
#                            .seq file's basename) - see lib/golden.sh.
#                            After a passing run, compares its screenshots
#                            (pixel-exact, or within --fuzz) and a scrubbed
#                            run.log against <DIR>/<sequence-name>/, and
#                            fails the run on any mismatch. Meant to be
#                            committed to git, so "did this change since
#                            commit X" is just `git show X:<path>` plus
#                            this same comparison - no extra tooling needed
#                            for that part.
#   --update-golden          With --golden-dir, APPROVE this run's output
#                            as the new baseline instead of comparing
#                            against the existing one (overwrites it).
#   --fuzz PERCENT           Tolerance passed to ImageMagick's `compare
#                            -fuzz` for golden screenshot comparison
#                            (default 0 - exact match). Only meaningful
#                            with --golden-dir.
#   --mask-rect WxH+X+Y      Black out this pixel region on BOTH images
#                            before golden comparison (see lib/golden.sh's
#                            _mask_rect_apply) - use it to exclude a
#                            screen region expected to vary run-to-run
#                            regardless of behavior, e.g. a clock/status
#                            bar. This is the RECOMMENDED way to get
#                            reproducible golden screenshots - unlike
#                            pinning the emulator's clock (see the note
#                            below), masking works for every sequence,
#                            including ones that wait for a real timer to
#                            fire, since it never touches the emulator's
#                            actual clock at all. Stored golden PNGs and
#                            this run's own screenshots are left
#                            untouched on disk either way - only
#                            throwaway temp copies are masked for the
#                            comparison itself. Only meaningful with
#                            --golden-dir.
#   -h, --help               Show this help.
#
# Any screen showing a live value (a clock, a bottom status bar, a running
# timer's countdown, ...) will never compare equal between two golden runs
# made at different real times unless made deterministic first - this
# framework does NOT do that for you automatically at the sequence-file
# level. Preferred: an app-side test hook that freezes what gets DRAWN,
# decoupled from the real clock (this project's own app has one - see its
# README/CLAUDE.md); falls back to `pebble emu-set-time HH:MM:SS` (a real
# pebble-tool subcommand, independent of app code) as an explicit
# `CMD emu-set-time ...` step right after INSTALL otherwise - see the main
# README's "Golden-file regression testing" section for the tradeoffs
# between the two (the emu-set-time approach is fundamentally incompatible
# with any sequence that waits for a REAL timer to fire).
#
# If a sequence does pin the clock, be aware of what THIS runner then does
# automatically: it re-pins immediately before every SCREENSHOT step (see
# lib/steps.sh's run_screenshot/_clock_pin_repin_if_active), because a
# single `CMD emu-set-time` at setup does NOT survive on its own -
# pebble-tool re-syncs the emulator's clock to the HOST's real time on
# every connection made through pypkjs (confirmed: TAP/APPMSG trigger
# this, SCREENSHOT/CMD emu-set-time itself do not). That per-screenshot
# re-pin is exactly what breaks real-timer-firing sequences: it yanks the
# clock backward from wherever the natural resync had just moved it
# (real host time) back to the fixed pin, and Pebble OS's real wakeup
# subsystem treats that backward jump as the watch having been off,
# surfacing its own genuine "while your Pebble was off" system screen
# instead of this app's alarm screen.
set -u

FRAMEWORK_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/log.sh
source "$FRAMEWORK_DIR/lib/log.sh"
# shellcheck source=lib/parse.sh
source "$FRAMEWORK_DIR/lib/parse.sh"
# shellcheck source=lib/steps.sh
source "$FRAMEWORK_DIR/lib/steps.sh"
# shellcheck source=lib/golden.sh
source "$FRAMEWORK_DIR/lib/golden.sh"

usage() {
  sed -n '2,91p' "$0" | sed 's/^# \{0,1\}//'
}

CONF_FILE=""
SEQ_FILE=""
PLATFORM_OVERRIDE=""
VNC_OVERRIDE=""
OUT_DIR_OVERRIDE=""
RUN_ID_OVERRIDE=""
CONTINUE_ON_ERROR=0
GOLDEN_DIR=""
UPDATE_GOLDEN=0
FUZZ="0"
MASK_RECT=""

while [ $# -gt 0 ]; do
  case "$1" in
    --conf) CONF_FILE="$2"; shift 2 ;;
    --seq) SEQ_FILE="$2"; shift 2 ;;
    --platform) PLATFORM_OVERRIDE="$2"; shift 2 ;;
    --vnc) VNC_OVERRIDE="1"; shift ;;
    --no-vnc) VNC_OVERRIDE="0"; shift ;;
    --out-dir) OUT_DIR_OVERRIDE="$2"; shift 2 ;;
    --run-id) RUN_ID_OVERRIDE="$2"; shift 2 ;;
    --continue-on-error) CONTINUE_ON_ERROR=1; shift ;;
    --golden-dir) GOLDEN_DIR="$2"; shift 2 ;;
    --update-golden) UPDATE_GOLDEN=1; shift ;;
    --fuzz) FUZZ="$2"; shift 2 ;;
    --mask-rect) MASK_RECT="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage; exit 1 ;;
  esac
done

if [ "$UPDATE_GOLDEN" = "1" ] && [ -z "$GOLDEN_DIR" ]; then
  echo "--update-golden requires --golden-dir." >&2
  usage
  exit 1
fi

if [ -z "$CONF_FILE" ] || [ -z "$SEQ_FILE" ]; then
  echo "Both --conf and --seq are required." >&2
  usage
  exit 1
fi
if [ ! -f "$CONF_FILE" ]; then
  echo "Conf file not found: $CONF_FILE" >&2
  exit 1
fi
if [ ! -f "$SEQ_FILE" ]; then
  echo "Sequence file not found: $SEQ_FILE" >&2
  exit 1
fi

# Conf file is a plain KEY=value file (APP_UUID=..., PLATFORM=..., VNC=0|1).
# shellcheck source=/dev/null
source "$CONF_FILE"

PLATFORM="${PLATFORM_OVERRIDE:-${PLATFORM:-emery}}"
VNC="${VNC_OVERRIDE:-${VNC:-1}}"
: "${APP_UUID:?APP_UUID must be set in $CONF_FILE}"

CONF_DIR="$(cd "$(dirname "$CONF_FILE")" && pwd)"
OUT_BASE="${OUT_DIR_OVERRIDE:-$CONF_DIR/out}"

# Sequence name - .seq file's basename, extension stripped (e.g.
# wakeup_conflict_basic_resolutions.seq -> wakeup_conflict_basic_
# resolutions) - used both for the golden baseline directory and to keep
# each sequence's own run output findable by name rather than only by
# timestamp.
SEQ_NAME="$(basename "$SEQ_FILE")"
SEQ_NAME="${SEQ_NAME%.seq}"
GOLDEN_SEQ_DIR="${GOLDEN_DIR:+$GOLDEN_DIR/$SEQ_NAME}"

# <out-dir>/<RUN_ID>/<sequence-name>/ - timestamp first, so a whole batch
# of sequences run together (see tests/functional/run_all.sh, which passes
# --run-id so every sequence in one invocation shares the same RUN_ID)
# lands under one shared, browsable directory instead of being scattered
# across a separate timestamp per sequence.
RUN_ID="${RUN_ID_OVERRIDE:-$(date '+%Y%m%d_%H%M%S')}"
RUN_OUT_DIR="$OUT_BASE/$RUN_ID/$SEQ_NAME"
mkdir -p "$RUN_OUT_DIR"
LOG_FILE="$RUN_OUT_DIR/run.log"
SCREENSHOT_COUNTER=0

# Persists a marker into this run's own output directory whenever it's
# running under the containerized harness (PEBBLE_TEST_CONTAINERIZED=1,
# set by tests/functional/docker/run-sequence-in-container.sh alongside
# its libfaketime env - see that script for why containerized execution
# is what makes screenshots/timing reproducible at all). A FILE, not just
# checking the env var live, because golden approval can happen in a
# LATER, separate process against an already-produced run dir
# (promote_golden.sh) - see update_golden()'s own guard in lib/golden.sh,
# which is what actually enforces this.
if [ "${PEBBLE_TEST_CONTAINERIZED:-}" = "1" ]; then
  : > "$RUN_OUT_DIR/.containerized"
fi

if [ -n "$GOLDEN_DIR" ]; then
  log_info "golden mode: comparing/updating $GOLDEN_SEQ_DIR (fuzz=${FUZZ}%) - remember to make any live displays deterministic yourself first (an app-side freeze hook, or a CMD emu-set-time step as a fallback); this runner does not do it for you"
fi

log_info "sequence: $SEQ_FILE"
log_info "platform=$PLATFORM vnc=$VNC app_uuid=$APP_UUID"
log_info "output dir: $RUN_OUT_DIR"

FLAT="$(flatten_sequence "$SEQ_FILE" "")"
FLATTEN_STATUS=$?
if [ "$FLATTEN_STATUS" -ne 0 ]; then
  log_error "failed to parse sequence (see above)"
  exit 1
fi

FAILED=0
while IFS=$'\t' read -r origin instruction; do
  [ -z "$instruction" ] && continue
  log_info "[$origin] $instruction"
  if ! dispatch_step "$origin" "$instruction"; then
    log_error "step failed at $origin: $instruction"
    FAILED=1
    [ "$CONTINUE_ON_ERROR" != "1" ] && break
  fi
done < <(printf '%s\n' "$FLAT")

if [ "$FAILED" = "1" ]; then
  log_error "sequence FAILED - log: $LOG_FILE"
  exit 1
fi

log_info "sequence PASSED - log: $LOG_FILE"

if [ -n "$GOLDEN_DIR" ]; then
  if [ "$UPDATE_GOLDEN" = "1" ]; then
    if ! update_golden "$RUN_OUT_DIR" "$GOLDEN_SEQ_DIR"; then
      exit 1
    fi
  else
    if ! compare_golden "$RUN_OUT_DIR" "$GOLDEN_SEQ_DIR" "$FUZZ" "$MASK_RECT"; then
      exit 1
    fi
  fi
fi
