#!/usr/bin/env bash
# Generic functional-test-sequence interpreter for Pebble apps.
#
# App-agnostic: everything app-specific (UUID, platform, whether to run
# --vnc by default, container image tag, build env, ...) comes from a
# small `--conf` KEY=value file, not from anything hardcoded here. See
# README.md in this directory for the full instruction-set reference and
# an app.conf example.
#
# Usage:
#   run_sequence.sh --conf <app.conf> --seq <sequence_file> [options]
#   run_sequence.sh --conf <app.conf> --build-only <dir> [--image-tag TAG]
#
# Options:
#   --conf FILE            App config file (see README.md for the full key
#                           reference: APP_UUID=, PLATFORM=, VNC=0|1,
#                           CONTAINER=0|1, IMAGE_TAG=, BUILD_ENV=,
#                           GOLDEN_DIR=).
#   --seq FILE              Top-level .seq file to run.
#   --platform NAME         Override PLATFORM from the conf file.
#   --vnc / --no-vnc         Override VNC from the conf file.
#   --out-dir DIR            Base output dir (default: <dir of conf>/out).
#   --run-id ID              Use this instead of generating a fresh
#                            timestamp for this run's output directory
#                            (<out-dir>/<ID>/<sequence-name>/) - lets a
#                            caller running several sequences as one batch
#                            (see run_batch.sh) group them all under one
#                            shared timestamp instead of each sequence
#                            getting its own. Default: a fresh
#                            `date +%Y%m%d_%H%M%S` generated by this run.
#   --continue-on-error      Keep running after a failed step instead of
#                            stopping immediately; reports a summary at the
#                            end.
#   --golden-dir DIR         Base dir of approved (golden) baselines, one
#                            subdirectory per sequence (named after the
#                            .seq file's basename) - see lib/golden.sh.
#                            After a passing run, compares its screenshots
#                            (pixel-exact, or within --fuzz) and a scrubbed
#                            run.log against <DIR>/<sequence-name>/, and
#                            fails the run on any mismatch. Meant to be
#                            committed to git, so "did this change since
#                            commit X" is just `git show X:<path>` plus
#                            this same comparison - no extra tooling needed
#                            for that part. Default: the conf file's own
#                            GOLDEN_DIR key, resolved relative to the conf
#                            file's directory, if set.
#   --update-golden          With --golden-dir, APPROVE this run's output
#                            as the new baseline instead of comparing
#                            against the existing one (overwrites it).
#   --fuzz PERCENT           Tolerance passed to ImageMagick's `compare
#                            -fuzz` for golden screenshot comparison
#                            (default 0 - exact match). Only meaningful
#                            with --golden-dir.
#   --mask-rect WxH+X+Y      Black out this pixel region on every
#                            screenshot THIS RUN CAPTURES (lib/steps.sh's
#                            run_screenshot/_mask_rect_apply), baked into
#                            the saved PNG itself at capture time - not
#                            applied later, only for comparison. A single
#                            SCREENSHOT step's own `SCREENSHOT label
#                            --mask-rect WxH+X+Y` overrides this whole-run
#                            default for just that one screenshot, so one
#                            screenshot's genuinely-expected non-
#                            determinism (e.g. the OS watchface's rotating
#                            hint text) doesn't force every OTHER
#                            screenshot in the same sequence to also mask
#                            that same screen region. Use either form to
#                            exclude a screen region expected to vary
#                            run-to-run regardless of behavior, e.g. a
#                            clock/status bar. This is the RECOMMENDED way
#                            to get reproducible golden screenshots -
#                            unlike pinning the emulator's clock (see the
#                            note below), masking works for every
#                            sequence, including ones that wait for a real
#                            timer to fire, since it never touches the
#                            emulator's actual clock at all. Because
#                            masking happens at capture time, a masked
#                            region is always the same deterministic solid
#                            black in every screenshot this produces,
#                            golden or not - golden-comparison itself
#                            (lib/golden.sh) has no mask awareness at all,
#                            it just compares files that already match in
#                            that region by construction. Meaningful for
#                            any run, not just one with --golden-dir -
#                            every SCREENSHOT this produces gets it, same
#                            as any other run.
#   --container / --no-container  Override the conf file's CONTAINER
#                            default for this run. Container mode runs the
#                            sequence inside a Podman/Docker image built
#                            from container/Containerfile instead of
#                            against a host-managed emulator - see
#                            container/README.md for the full "why"
#                            (deterministic clock, parallel-safe). Native
#                            mode (the default unless the conf file or this
#                            flag says otherwise) needs no container setup
#                            at all, at the cost of non-reproducible
#                            screenshots - never trust a golden comparison/
#                            approval made natively (update_golden()
#                            itself refuses to, see lib/golden.sh).
#   --image-tag TAG          Override the conf file's IMAGE_TAG for this
#                            run (container mode only).
#   --touch                  Starts Xvfb and runs the emulator without
#                            --vnc inside the container instead of the
#                            default --vnc-only path every other sequence
#                            uses (see container/README.md's performance
#                            note) - needed for a sequence using the
#                            TOUCH/TOUCHDOWN/TOUCHUP/TOUCHMOVE/TOUCHSWEEP/
#                            TOUCHDRAG instructions. Auto-detected by
#                            default (including through IMPORTs) in
#                            container mode - passing it explicitly is only
#                            needed to force touch mode on a sequence this
#                            detection doesn't catch. Container-only -
#                            rejected with --no-container, since a real
#                            touchscreen event only reaches the guest
#                            through a genuine SDL/X11 window an
#                            Xvfb-backed xdotool can target, which native
#                            mode has no supported way to provide.
#   --prebuilt-build DIR     Skip this container's own npm install +
#                            pebble build and reuse the build/ tree a
#                            prior --build-only DIR run already produced,
#                            mounted read-only. DIR must be the SAME
#                            directory passed to that --build-only call.
#                            Container-only. Exists for run_batch.sh's batch
#                            use (build once, reuse across every sequence
#                            container in the batch), not meant for
#                            standalone use.
#   --build-only DIR         Build once (npm install + pebble build) inside
#                            the project's container image and copy the
#                            result to DIR/build on the host, instead of
#                            running any sequence (no --seq needed with
#                            this). Used by run_batch.sh to build ONCE for a
#                            whole batch instead of once per sequence
#                            container. Always dispatches to the container,
#                            regardless of the conf file's own CONTAINER
#                            default - there is no "build-only" concept in
#                            native mode. Not meant to be used outside of
#                            run_batch.sh for standalone use.
#   -h, --help               Show this help.
#
# Any screen showing a live value (a clock, a bottom status bar, a running
# timer's countdown, ...) will never compare equal between two golden runs
# made at different real times unless made deterministic first - this
# framework does NOT do that for you automatically at the sequence-file
# level. Preferred: an app-side test hook that freezes what gets DRAWN,
# decoupled from the real clock; falls back to `pebble emu-set-time
# HH:MM:SS` (a real pebble-tool subcommand, independent of app code) as an
# explicit `CMD emu-set-time ...` step right after INSTALL otherwise - see
# README.md's "Golden-file regression testing" section for the tradeoffs
# between the two (the emu-set-time approach is fundamentally incompatible
# with any sequence that waits for a REAL timer to fire).
#
# If a sequence does pin the clock, be aware of what THIS runner then does
# automatically: it re-pins immediately before every SCREENSHOT step (see
# lib/steps.sh's run_screenshot/_clock_pin_repin_if_active), because a
# single `CMD emu-set-time` at setup does NOT survive on its own -
# pebble-tool re-syncs the emulator's clock to the HOST's real time on
# every connection made through pypkjs (confirmed: TAP/APPMSG trigger
# this, SCREENSHOT/CMD emu-set-time itself do not). That per-screenshot
# re-pin is exactly what breaks real-timer-firing sequences: it yanks the
# clock backward from wherever the natural resync had just moved it
# (real host time) back to the fixed pin, and Pebble OS's real wakeup
# subsystem treats that backward jump as the watch having been off,
# surfacing its own genuine "while your Pebble was off" system screen
# instead of the app's alarm screen. Container mode (see --container
# above) sidesteps this whole problem via libfaketime instead - see
# container/README.md.
set -u

FRAMEWORK_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/log.sh
source "$FRAMEWORK_DIR/lib/log.sh"
# shellcheck source=lib/parse.sh
source "$FRAMEWORK_DIR/lib/parse.sh"
# shellcheck source=lib/steps.sh
source "$FRAMEWORK_DIR/lib/steps.sh"
# shellcheck source=lib/golden.sh
source "$FRAMEWORK_DIR/lib/golden.sh"

usage() {
  sed -n '2,165p' "$0" | sed 's/^# \{0,1\}//'
}

CONF_FILE=""
SEQ_FILE=""
PLATFORM_OVERRIDE=""
VNC_OVERRIDE=""
OUT_DIR_OVERRIDE=""
RUN_ID_OVERRIDE=""
CONTINUE_ON_ERROR=0
GOLDEN_DIR_OVERRIDE=""
UPDATE_GOLDEN=0
FUZZ="0"
MASK_RECT=""
CONTAINER_OVERRIDE=""
IMAGE_TAG_OVERRIDE=""
TOUCH_REQUESTED=0
PREBUILT_BUILD_DIR=""
BUILD_ONLY_DIR=""

while [ $# -gt 0 ]; do
  case "$1" in
    --conf) CONF_FILE="$2"; shift 2 ;;
    --seq) SEQ_FILE="$2"; shift 2 ;;
    --platform) PLATFORM_OVERRIDE="$2"; shift 2 ;;
    --vnc) VNC_OVERRIDE="1"; shift ;;
    --no-vnc) VNC_OVERRIDE="0"; shift ;;
    --out-dir) OUT_DIR_OVERRIDE="$2"; shift 2 ;;
    --run-id) RUN_ID_OVERRIDE="$2"; shift 2 ;;
    --continue-on-error) CONTINUE_ON_ERROR=1; shift ;;
    --golden-dir) GOLDEN_DIR_OVERRIDE="$2"; shift 2 ;;
    --update-golden) UPDATE_GOLDEN=1; shift ;;
    --fuzz) FUZZ="$2"; shift 2 ;;
    --mask-rect) MASK_RECT="$2"; shift 2 ;;
    --container) CONTAINER_OVERRIDE="1"; shift ;;
    --no-container) CONTAINER_OVERRIDE="0"; shift ;;
    --image-tag) IMAGE_TAG_OVERRIDE="$2"; shift 2 ;;
    --touch) TOUCH_REQUESTED=1; shift ;;
    --prebuilt-build) PREBUILT_BUILD_DIR="$2"; shift 2 ;;
    --build-only) BUILD_ONLY_DIR="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage; exit 1 ;;
  esac
done

if [ "$UPDATE_GOLDEN" = "1" ] && [ -z "$GOLDEN_DIR_OVERRIDE" ]; then
  echo "--update-golden requires --golden-dir." >&2
  usage
  exit 1
fi

if [ -z "$CONF_FILE" ]; then
  echo "--conf is required." >&2
  usage
  exit 1
fi
if [ -z "$BUILD_ONLY_DIR" ] && [ -z "$SEQ_FILE" ]; then
  echo "--seq is required unless --build-only is given." >&2
  usage
  exit 1
fi
if [ ! -f "$CONF_FILE" ]; then
  echo "Conf file not found: $CONF_FILE" >&2
  exit 1
fi
if [ -n "$SEQ_FILE" ] && [ ! -f "$SEQ_FILE" ]; then
  echo "Sequence file not found: $SEQ_FILE" >&2
  exit 1
fi

# Resolve to absolute, canonical paths now - needed both for the
# container-dispatch branch below (to compute paths relative to the repo
# root) and so a relative --conf/--seq still works regardless of the
# caller's own cwd.
CONF_FILE="$(cd "$(dirname "$CONF_FILE")" && pwd)/$(basename "$CONF_FILE")"
[ -n "$SEQ_FILE" ] && SEQ_FILE="$(cd "$(dirname "$SEQ_FILE")" && pwd)/$(basename "$SEQ_FILE")"

# Conf file is a plain KEY=value file (APP_UUID=..., PLATFORM=..., VNC=0|1,
# CONTAINER=0|1, IMAGE_TAG=..., SDK_VERSION=..., BUILD_ENV=...,
# GOLDEN_DIR=..., SEQ_DIR=...) - see README.md for the full reference.
# shellcheck source=/dev/null
source "$CONF_FILE"

PLATFORM="${PLATFORM_OVERRIDE:-${PLATFORM:-emery}}"
VNC="${VNC_OVERRIDE:-${VNC:-1}}"
: "${APP_UUID:?APP_UUID must be set in $CONF_FILE}"
CONTAINER="${CONTAINER_OVERRIDE:-${CONTAINER:-0}}"
IMAGE_TAG="${IMAGE_TAG_OVERRIDE:-${IMAGE_TAG:-pebble-functional-tests-$APP_UUID}}"
BUILD_ENV="${BUILD_ENV:-}"
# Captured before being overwritten below - the conf file (just sourced)
# may have set its own GOLDEN_DIR=... key, which this script's own
# resolved GOLDEN_DIR variable (below) otherwise shadows.
GOLDEN_DIR_FROM_CONF="${GOLDEN_DIR:-}"

CONF_DIR="$(cd "$(dirname "$CONF_FILE")" && pwd)"
OUT_BASE="${OUT_DIR_OVERRIDE:-$CONF_DIR/out}"

# GOLDEN_DIR_OVERRIDE (--golden-dir) wins; otherwise the conf file's own
# GOLDEN_DIR key (resolved relative to the conf file's own directory,
# unless already absolute) is the default; otherwise golden comparison is
# simply off for this run, same as before this key existed.
GOLDEN_DIR=""
if [ -n "$GOLDEN_DIR_OVERRIDE" ]; then
  GOLDEN_DIR="$GOLDEN_DIR_OVERRIDE"
elif [ -n "$GOLDEN_DIR_FROM_CONF" ]; then
  case "$GOLDEN_DIR_FROM_CONF" in
    /*) GOLDEN_DIR="$GOLDEN_DIR_FROM_CONF" ;;
    *) GOLDEN_DIR="$CONF_DIR/$GOLDEN_DIR_FROM_CONF" ;;
  esac
fi

if [ "$TOUCH_REQUESTED" != "1" ] && [ -n "$SEQ_FILE" ]; then
  # Auto-detect sequences that actually need --touch (any TOUCH/TOUCHDOWN/
  # TOUCHUP/TOUCHMOVE/TOUCHSWEEP/TOUCHDRAG instruction - see README.md's
  # instruction-set reference), including through IMPORTs, instead of
  # requiring every caller to remember and pass --touch by hand. An
  # explicit --touch above still wins (this only runs if it wasn't given) -
  # this is purely a default, not the only way to request touch mode.
  if FLAT_FOR_TOUCH="$(flatten_sequence "$SEQ_FILE" "" 2>/dev/null)" \
      && printf '%s\n' "$FLAT_FOR_TOUCH" | cut -f2- | awk '{print $1}' | grep -q '^TOUCH'; then
    TOUCH_REQUESTED=1
  fi
fi

# --- Container dispatch ---
# --build-only always means "build the shared container image's build
# tree" - there is no native equivalent, so it dispatches regardless of
# the conf file's own CONTAINER default. Otherwise, dispatch only if
# CONTAINER=1 for this run AND we're not already running INSIDE the
# container (PEBBLE_TEST_CONTAINERIZED=1, set by container/entrypoint.sh
# right before it re-invokes this very script) - that second check is what
# makes container/entrypoint.sh's re-invocation actually run the sequence
# instead of looping back into launch.sh forever.
if [ -n "$BUILD_ONLY_DIR" ] || { [ "$CONTAINER" = "1" ] && [ "${PEBBLE_TEST_CONTAINERIZED:-0}" != "1" ]; }; then
  REPO_ROOT="$(git -C "$CONF_DIR" rev-parse --show-toplevel 2>/dev/null)" || {
    echo "Container mode requires the project to be a git repository (to resolve the repo root for mounting into the container)." >&2
    exit 1
  }
  FRAMEWORK_REL="${FRAMEWORK_DIR#"$REPO_ROOT"/}"

  LAUNCH_ARGS=(--repo-root "$REPO_ROOT" --framework-rel "$FRAMEWORK_REL" --image-tag "$IMAGE_TAG")
  [ -n "$BUILD_ENV" ] && LAUNCH_ARGS+=(--build-env "$BUILD_ENV")

  if [ -n "$BUILD_ONLY_DIR" ]; then
    LAUNCH_ARGS+=(--build-only "$BUILD_ONLY_DIR")
  else
    CONF_REL="${CONF_FILE#"$REPO_ROOT"/}"
    SEQ_REL="${SEQ_FILE#"$REPO_ROOT"/}"
    LAUNCH_ARGS+=(--conf-rel "$CONF_REL" --seq-rel "$SEQ_REL" --out-dir "$OUT_BASE")
    [ -n "$GOLDEN_DIR" ] && LAUNCH_ARGS+=(--golden-dir "$GOLDEN_DIR")
    [ -n "$RUN_ID_OVERRIDE" ] && LAUNCH_ARGS+=(--run-id "$RUN_ID_OVERRIDE")
    [ "$TOUCH_REQUESTED" = "1" ] && LAUNCH_ARGS+=(--touch)
    [ -n "$PREBUILT_BUILD_DIR" ] && LAUNCH_ARGS+=(--prebuilt-build "$PREBUILT_BUILD_DIR")

    FORWARD_ARGS=(--fuzz "$FUZZ")
    [ "$UPDATE_GOLDEN" = "1" ] && FORWARD_ARGS+=(--update-golden)
    [ -n "$MASK_RECT" ] && FORWARD_ARGS+=(--mask-rect "$MASK_RECT")
    [ "$CONTINUE_ON_ERROR" = "1" ] && FORWARD_ARGS+=(--continue-on-error)
    [ -n "$PLATFORM_OVERRIDE" ] && FORWARD_ARGS+=(--platform "$PLATFORM_OVERRIDE")
    if [ -n "$VNC_OVERRIDE" ]; then
      if [ "$VNC_OVERRIDE" = "1" ]; then FORWARD_ARGS+=(--vnc); else FORWARD_ARGS+=(--no-vnc); fi
    fi
    LAUNCH_ARGS+=(-- "${FORWARD_ARGS[@]}")
  fi

  exec "$FRAMEWORK_DIR/container/launch.sh" "${LAUNCH_ARGS[@]}"
fi

# Reached either in genuine native mode, or inside the container after
# container/entrypoint.sh's own re-invocation (PEBBLE_TEST_CONTAINERIZED=1)
# - --touch/--prebuilt-build are container-only concepts with no native
# equivalent, so reject them in the genuine-native case rather than
# silently ignoring them. Inside the container, TOUCH_REQUESTED may well
# be 1 again here (this script's own auto-detection re-runs on every
# invocation) - that's expected and harmless: Xvfb is already running
# there based on the PEBBLE_TEST_TOUCH env var container/entrypoint.sh set
# before this re-invocation, not on this flag.
if [ "${PEBBLE_TEST_CONTAINERIZED:-0}" != "1" ]; then
  if [ "$TOUCH_REQUESTED" = "1" ]; then
    echo "--touch is incompatible with native (--no-container) mode: a real touchscreen event only reaches the guest through a genuine SDL/X11 window (Xvfb+xdotool, container-only) - qemu's --vnc framebuffer never delivers touch input, and there is no supported native equivalent (see container/Containerfile's own comment)." >&2
    exit 1
  fi
  if [ -n "$PREBUILT_BUILD_DIR" ]; then
    echo "--prebuilt-build is incompatible with native (--no-container) mode: there's no per-container build to skip." >&2
    exit 1
  fi
fi

# Sequence name - .seq file's basename, extension stripped (e.g.
# wakeup_conflict_basic_resolutions.seq -> wakeup_conflict_basic_
# resolutions) - used both for the golden baseline directory and to keep
# each sequence's own run output findable by name rather than only by
# timestamp.
SEQ_NAME="$(basename "$SEQ_FILE")"
SEQ_NAME="${SEQ_NAME%.seq}"
GOLDEN_SEQ_DIR="${GOLDEN_DIR:+$GOLDEN_DIR/$SEQ_NAME}"

# <out-dir>/<RUN_ID>/<sequence-name>/ - timestamp first, so a whole batch
# of sequences run together (see run_batch.sh, which passes --run-id so
# every sequence in one invocation shares the same RUN_ID) lands under one
# shared, browsable directory instead of being scattered across a separate
# timestamp per sequence.
RUN_ID="${RUN_ID_OVERRIDE:-$(date '+%Y%m%d_%H%M%S')}"
RUN_OUT_DIR="$OUT_BASE/$RUN_ID/$SEQ_NAME"
mkdir -p "$RUN_OUT_DIR"
LOG_FILE="$RUN_OUT_DIR/run.log"
SCREENSHOT_COUNTER=0

# Persists a marker into this run's own output directory whenever it's
# running under the containerized harness (PEBBLE_TEST_CONTAINERIZED=1,
# set by container/entrypoint.sh alongside its libfaketime env - see that
# script for why containerized execution is what makes screenshots/timing
# reproducible at all). A FILE, not just checking the env var live,
# because golden approval can happen in a LATER, separate process against
# an already-produced run dir (promote_golden.sh) - see
# update_golden()'s own guard in lib/golden.sh, which is what actually
# enforces this.
if [ "${PEBBLE_TEST_CONTAINERIZED:-}" = "1" ]; then
  : > "$RUN_OUT_DIR/.containerized"
fi

if [ -n "$GOLDEN_DIR" ]; then
  log_info "golden mode: comparing/updating $GOLDEN_SEQ_DIR (fuzz=${FUZZ}%) - remember to make any live displays deterministic yourself first (an app-side freeze hook, or a CMD emu-set-time step as a fallback); this runner does not do it for you"
fi

log_info "sequence: $SEQ_FILE"
log_info "platform=$PLATFORM vnc=$VNC app_uuid=$APP_UUID"
log_info "output dir: $RUN_OUT_DIR"

FLAT="$(flatten_sequence "$SEQ_FILE" "")"
FLATTEN_STATUS=$?
if [ "$FLATTEN_STATUS" -ne 0 ]; then
  log_error "failed to parse sequence (see above)"
  exit 1
fi

FAILED=0
while IFS=$'\t' read -r origin instruction; do
  [ -z "$instruction" ] && continue
  log_info "[$origin] $instruction"
  if ! dispatch_step "$origin" "$instruction"; then
    log_error "step failed at $origin: $instruction"
    FAILED=1
    [ "$CONTINUE_ON_ERROR" != "1" ] && break
  fi
done < <(printf '%s\n' "$FLAT")

if [ "$FAILED" = "1" ]; then
  log_error "sequence FAILED - log: $LOG_FILE"
  exit 1
fi

log_info "sequence PASSED - log: $LOG_FILE"

if [ -n "$GOLDEN_DIR" ]; then
  if [ "$UPDATE_GOLDEN" = "1" ]; then
    if ! update_golden "$RUN_OUT_DIR" "$GOLDEN_SEQ_DIR"; then
      exit 1
    fi
  else
    if ! compare_golden "$RUN_OUT_DIR" "$GOLDEN_SEQ_DIR" "$FUZZ"; then
      exit 1
    fi
  fi
fi
